# Generated by Django 5.2.4 on 2025-07-22 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10)),
                ('name_agency', models.CharField(max_length=100)),
                ('email_agency', models.EmailField(max_length=100)),
                ('tel_agency', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=100)),
                ('num_doc', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=200, null=True)),
                ('hotel', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10)),
                ('name_provider', models.CharField(max_length=100)),
                ('email_provider', models.EmailField(max_length=100)),
                ('tel_provider', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(max_length=10)),
                ('num_doc', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('client_data', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=100)),
                ('type_count', models.CharField(max_length=100)),
                ('num_count', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(max_length=10)),
                ('num_doc', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_sale_unit', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_sale', models.FloatField()),
                ('observations', models.CharField(default='', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.client')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.referrer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_payment', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('beneficiary_num', models.CharField(max_length=100)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('value_sale', models.FloatField()),
                ('value_commission', models.FloatField()),
                ('observations', models.CharField(default='', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price_sale', models.FloatField()),
                ('price_total', models.FloatField()),
                ('image_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='sales.agency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='sales.provider')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.tour'),
        ),
        migrations.AddField(
            model_name='sale',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.vendor'),
        ),
    ]
