# Generated by Django 5.2.4 on 2025-07-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tipo_doc',
        ),
        migrations.AddField(
            model_name='client',
            name='type_doc',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PP', 'Pasaporte'), ('NIT', 'NIT')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
