# Generated by Django 5.2.4 on 2025-07-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='date_tour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Tour'),
        ),
    ]
