# Generated by Django 5.2.4 on 2025-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
