# Generated by Django 5.2.4 on 2025-08-05 12:53

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_payment_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=sales.models.tour_main_image_upload_path),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image_path',
            field=models.ImageField(upload_to=sales.models.tour_image_upload_path),
        ),
    ]
