# Generated by Django 5.2.4 on 2025-08-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_tour_image_path_alter_tourimage_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
